export const LANGUAGES = {
  en: {
    appName: 'Prime',
    selectLanguage: 'Select Language',
    dashboard: 'Brain Training',
    // Original challenges
    numberTap: 'Number Tap',
    mathSprint: 'Math Sprint', 
    memoryNumbers: 'Memory Numbers',
    patternMatch: 'Pattern Match',
    // New challenges
    memoryMatrix: 'Memory Matrix',
    patternPath: 'Pattern Path',
    primeHunter: 'Prime Hunter',
    sequenceMaster: 'Sequence Master',
    divisionChallenge: 'Division Master',
    mentalArithmetic: 'Mental Arithmetic',
    mathFactMaster: 'Math Facts',
    infiniteMathZen: 'Math Zen',
    mathStream: 'Math Stream',
    reflexRush: 'Reflex Rush',
    // Common game terms
    time: 'Time',
    best: 'Best',
    tap: 'Tap',
    start: 'Start!',
    tapping: 'Tapping...',
    newRecord: '🎉 New Record!',
    completed: '✅ Completed!',
    timeText: 'Time',
    bestText: 'Best',
    description: 'Tap numbers 1-25 in order as fast as you can!',
    back: 'Back',
    score: 'Score',
    level: 'Level',
    correct: 'Correct!',
    wrong: 'Wrong!',
    remember: 'Remember the sequence!',
    yourTurn: 'Your turn!',
    patternComplete: 'Pattern Complete!',
    solve: 'Solve:',
    answer: 'Answer',
    next: 'Next',
    // New game terms
    streak: 'Streak',
    lives: 'Lives',
    gameOver: 'Game Over',
    playAgain: 'Play Again',
    continue: 'Continue',
    quit: 'Quit',
    restart: 'Restart',
    highScore: 'High Score',
    average: 'Average',
    reaction: 'Reaction',
    speed: 'Speed',
    memory: 'Memory',
    logic: 'Logic',
    math: 'Math',
    reflex: 'Reflex',
    // Challenge descriptions
    memoryMatrixDesc: 'Remember tile patterns',
    patternPathDesc: 'Complete visual patterns',
    primeHunterDesc: 'Find prime numbers',
    sequenceMasterDesc: 'Identify number patterns',
    divisionChallengeDesc: 'Division practice',
    mentalArithmeticDesc: 'Mixed operations',
    mathFactMasterDesc: 'Master basic facts',
    infiniteMathZenDesc: 'Relaxing endless math',
    mathStreamDesc: 'Endless math challenge',
    reflexRushDesc: 'React to colors & shapes'
  },
  es: {
    appName: 'Prime',
    selectLanguage: 'Seleccionar Idioma',
    dashboard: 'Entrenamiento Cerebral',
    // Original challenges
    numberTap: 'Toque de Números',
    mathSprint: 'Carrera Matemática',
    memoryNumbers: 'Números de Memoria',
    patternMatch: 'Coincidencia de Patrones',
    // New challenges
    memoryMatrix: 'Matriz de Memoria',
    patternPath: 'Camino de Patrones',
    primeHunter: 'Cazador de Primos',
    sequenceMaster: 'Maestro de Secuencias',
    divisionChallenge: 'Maestro de División',
    mentalArithmetic: 'Aritmética Mental',
    mathFactMaster: 'Hechos Matemáticos',
    infiniteMathZen: 'Zen Matemático',
    mathStream: 'Flujo Matemático',
    reflexRush: 'Carrera de Reflejos',
    // Common game terms
    time: 'Tiempo',
    best: 'Mejor',
    tap: 'Toca',
    start: '¡Comenzar!',
    tapping: 'Tocando...',
    newRecord: '🎉 Nuevo Record!',
    completed: '✅ Completado!',
    timeText: 'Tiempo',
    bestText: 'Mejor',
    description: '¡Toca los números 1-25 en orden lo más rápido que puedas!',
    back: 'Atrás',
    score: 'Puntuación',
    level: 'Nivel',
    correct: '¡Correcto!',
    wrong: '¡Incorrecto!',
    remember: '¡Recuerda la secuencia!',
    yourTurn: '¡Tu turno!',
    patternComplete: '¡Patrón Completado!',
    solve: 'Resuelve:',
    answer: 'Respuesta',
    next: 'Siguiente',
    // New game terms
    streak: 'Racha',
    lives: 'Vidas',
    gameOver: 'Juego Terminado',
    playAgain: 'Jugar de Nuevo',
    continue: 'Continuar',
    quit: 'Salir',
    restart: 'Reiniciar',
    highScore: 'Puntuación Alta',
    average: 'Promedio',
    reaction: 'Reacción',
    speed: 'Velocidad',
    memory: 'Memoria',
    logic: 'Lógica',
    math: 'Matemáticas',
    reflex: 'Reflejo'
  },
  fr: {
    appName: 'Prime',
    selectLanguage: 'Choisir la Langue',
    dashboard: 'Entraînement Cérébral',
    // Original challenges
    numberTap: 'Tap Numérique',
    mathSprint: 'Course Mathématique',
    memoryNumbers: 'Mémoire des Nombres',
    patternMatch: 'Modèle à Suivre',
    // New challenges
    memoryMatrix: 'Matrice de Mémoire',
    patternPath: 'Chemin des Motifs',
    primeHunter: 'Chasseur de Nombres Premiers',
    sequenceMaster: 'Maître des Séquences',
    divisionChallenge: 'Maître de Division',
    mentalArithmetic: 'Arithmétique Mentale',
    mathFactMaster: 'Faits Mathématiques',
    infiniteMathZen: 'Zen Mathématique',
    mathStream: 'Flux Mathématique',
    reflexRush: 'Course de Réflexes',
    // Common game terms
    time: 'Temps',
    best: 'Meilleur',
    tap: 'Appuyez',
    start: 'Commencer!',
    tapping: 'En cours...',
    newRecord: '🎉 Nouveau Record!',
    completed: '✅ Terminé!',
    timeText: 'Temps',
    bestText: 'Meilleur',
    description: 'Appuyez sur les nombres 1-25 dans l\'ordre le plus vite possible!',
    back: 'Retour',
    score: 'Score',
    level: 'Niveau',
    correct: 'Correct!',
    wrong: 'Faux!',
    remember: 'Souviens-toi de la séquence!',
    yourTurn: 'À ton tour!',
    patternComplete: 'Modèle Terminé!',
    solve: 'Résoudre:',
    answer: 'Réponse',
    next: 'Suivant',
    // New game terms
    streak: 'Série',
    lives: 'Vies',
    gameOver: 'Jeu Terminé',
    playAgain: 'Rejouer',
    continue: 'Continuer',
    quit: 'Quitter',
    restart: 'Redémarrer',
    highScore: 'Meilleur Score',
    average: 'Moyenne',
    reaction: 'Réaction',
    speed: 'Vitesse',
    memory: 'Mémoire',
    logic: 'Logique',
    math: 'Maths',
    reflex: 'Réflexe'
  },
  de: {
    appName: 'Prime',
    selectLanguage: 'Sprache Auswählen',
    dashboard: 'Gehirntraining',
    // Original challenges
    numberTap: 'Zahlen Tippen',
    mathSprint: 'Mathe-Sprint',
    memoryNumbers: 'Zahlen Gedächtnis',
    patternMatch: 'Muster Erkennen',
    // New challenges
    memoryMatrix: 'Gedächtnis-Matrix',
    patternPath: 'Muster-Pfad',
    primeHunter: 'Primzahl-Jäger',
    sequenceMaster: 'Sequenz-Meister',
    divisionChallenge: 'Divisions-Meister',
    mentalArithmetic: 'Kopfrechnen',
    mathFactMaster: 'Mathe-Fakten',
    infiniteMathZen: 'Mathe-Zen',
    mathStream: 'Mathe-Strom',
    reflexRush: 'Reflex-Rausch',
    // Common game terms
    time: 'Zeit',
    best: 'Beste',
    tap: 'Tippen',
    start: 'Starten!',
    tapping: 'Tippen...',
    newRecord: '🎉 Neuer Rekord!',
    completed: '✅ Abgeschlossen!',
    timeText: 'Zeit',
    bestText: 'Beste',
    description: 'Tippe die Zahlen 1-25 in der richtigen Reihenfolge so schnell wie möglich!',
    back: 'Zurück',
    score: 'Punktzahl',
    level: 'Level',
    correct: 'Richtig!',
    wrong: 'Falsch!',
    remember: 'Merke dir die Sequenz!',
    yourTurn: 'Du bist dran!',
    patternComplete: 'Muster Vollständig!',
    solve: 'Löse:',
    answer: 'Antwort',
    next: 'Weiter',
    // New game terms
    streak: 'Serie',
    lives: 'Leben',
    gameOver: 'Spiel Beendet',
    playAgain: 'Nochmal Spielen',
    continue: 'Weiter',
    quit: 'Beenden',
    restart: 'Neustart',
    highScore: 'Highscore',
    average: 'Durchschnitt',
    reaction: 'Reaktion',
    speed: 'Geschwindigkeit',
    memory: 'Gedächtnis',
    logic: 'Logik',
    math: 'Mathe',
    reflex: 'Reflex'
  },
  it: {
    appName: 'Prime',
    selectLanguage: 'Seleziona Lingua',
    dashboard: 'Allenamento Mentale',
    // Original challenges
    numberTap: 'Tocco Numerico',
    mathSprint: 'Corsa Matematica',
    memoryNumbers: 'Memoria Numerica',
    patternMatch: 'Corrispondenza Modelli',
    // New challenges
    memoryMatrix: 'Matrice di Memoria',
    patternPath: 'Percorso Modelli',
    primeHunter: 'Cacciatore di Primi',
    sequenceMaster: 'Maestro di Sequenze',
    divisionChallenge: 'Maestro di Divisione',
    mentalArithmetic: 'Aritmetica Mentale',
    mathFactMaster: 'Fatti Matematici',
    infiniteMathZen: 'Zen Matematico',
    mathStream: 'Flusso Matematico',
    reflexRush: 'Corsa di Riflessi',
    // Common game terms
    time: 'Tempo',
    best: 'Migliore',
    tap: 'Tocca',
    start: 'Iniziare!',
    tapping: 'Toccando...',
    newRecord: '🎉 Nuovo Record!',
    completed: '✅ Completato!',
    timeText: 'Tempo',
    bestText: 'Migliore',
    description: 'Tocca i numeri 1-25 in ordine il più velocemente possibile!',
    back: 'Indietro',
    score: 'Punteggio',
    level: 'Livello',
    correct: 'Corretto!',
    wrong: 'Sbagliato!',
    remember: 'Ricorda la sequenza!',
    yourTurn: 'Il tuo turno!',
    patternComplete: 'Modello Completato!',
    solve: 'Risolvi:',
    answer: 'Risposta',
    next: 'Avanti',
    // New game terms
    streak: 'Serie',
    lives: 'Vite',
    gameOver: 'Gioco Terminato',
    playAgain: 'Gioca di Nuovo',
    continue: 'Continua',
    quit: 'Esci',
    restart: 'Riavvia',
    highScore: 'Punteggio Alto',
    average: 'Media',
    reaction: 'Reazione',
    speed: 'Velocità',
    memory: 'Memoria',
    logic: 'Logica',
    math: 'Matematica',
    reflex: 'Riflesso'
  },
  pt: {
    appName: 'Prime',
    selectLanguage: 'Selecionar Idioma',
    dashboard: 'Treino Cerebral',
    // Original challenges
    numberTap: 'Toque Numérico',
    mathSprint: 'Corrida Matemática',
    memoryNumbers: 'Memória Numérica',
    patternMatch: 'Combinação de Padrões',
    // New challenges
    memoryMatrix: 'Matriz de Memória',
    patternPath: 'Caminho de Padrões',
    primeHunter: 'Caçador de Primos',
    sequenceMaster: 'Mestre de Sequências',
    divisionChallenge: 'Mestre de Divisão',
    mentalArithmetic: 'Aritmética Mental',
    mathFactMaster: 'Fatos Matemáticos',
    infiniteMathZen: 'Zen Matemático',
    mathStream: 'Fluxo Matemático',
    reflexRush: 'Corrida de Reflexos',
    // Common game terms
    time: 'Tempo',
    best: 'Melhor',
    tap: 'Toque',
    start: 'Começar!',
    tapping: 'Tocando...',
    newRecord: '🎉 Novo Recorde!',
    completed: '✅ Concluído!',
    timeText: 'Tempo',
    bestText: 'Melhor',
    description: 'Toque nos números 1-25 em ordem o mais rápido que puder!',
    back: 'Voltar',
    score: 'Pontuação',
    level: 'Nível',
    correct: 'Correto!',
    wrong: 'Errado!',
    remember: 'Lembre-se da sequência!',
    yourTurn: 'Sua vez!',
    patternComplete: 'Padrão Concluído!',
    solve: 'Resolva:',
    answer: 'Resposta',
    next: 'Próximo',
    // New game terms
    streak: 'Sequência',
    lives: 'Vidas',
    gameOver: 'Fim de Jogo',
    playAgain: 'Jogar Novamente',
    continue: 'Continuar',
    quit: 'Sair',
    restart: 'Reiniciar',
    highScore: 'Pontuação Alta',
    average: 'Média',
    reaction: 'Reação',
    speed: 'Velocidade',
    memory: 'Memória',
    logic: 'Lógica',
    math: 'Matemática',
    reflex: 'Reflexo'
  },
  ja: {
    appName: 'Prime',
    selectLanguage: '言語を選択',
    dashboard: '脳トレーニング',
    // Original challenges
    numberTap: '数字タップ',
    mathSprint: '計算スプリント',
    memoryNumbers: '数字記憶',
    patternMatch: 'パターンマッチ',
    // New challenges
    memoryMatrix: '記憶マトリックス',
    patternPath: 'パターンパス',
    primeHunter: '素数ハンター',
    sequenceMaster: 'シーケンスマスター',
    divisionChallenge: '割り算マスター',
    mentalArithmetic: '暗算',
    mathFactMaster: '数学ファクト',
    infiniteMathZen: '数学禅',
    mathStream: '数学ストリーム',
    reflexRush: '反射ラッシュ',
    // Common game terms
    time: '時間',
    best: 'ベスト',
    tap: 'タップ',
    start: 'スタート!',
    tapping: 'タップ中...',
    newRecord: '🎉 新記録!',
    completed: '✅ 完了!',
    timeText: '時間',
    bestText: 'ベスト',
    description: '1から25までの数字を順番に素早くタップしてください！',
    back: '戻る',
    score: 'スコア',
    level: 'レベル',
    correct: '正解!',
    wrong: '不正解!',
    remember: 'シーケンスを覚えて！',
    yourTurn: 'あなたの番！',
    patternComplete: 'パターン完了！',
    solve: '解決：',
    answer: '答え',
    next: '次へ',
    // New game terms
    streak: '連続',
    lives: 'ライフ',
    gameOver: 'ゲームオーバー',
    playAgain: '再プレイ',
    continue: '続ける',
    quit: '終了',
    restart: '再開',
    highScore: 'ハイスコア',
    average: '平均',
    reaction: '反応',
    speed: '速度',
    memory: '記憶',
    logic: '論理',
    math: '数学',
    reflex: '反射'
  },
  ko: {
    appName: 'Prime',
    selectLanguage: '언어 선택',
    dashboard: '두뇌 훈련',
    // Original challenges
    numberTap: '숫자 탭',
    mathSprint: '수학 스프린트',
    memoryNumbers: '숫자 기억',
    patternMatch: '패턴 매치',
    // New challenges
    memoryMatrix: '기억 매트릭스',
    patternPath: '패턴 경로',
    primeHunter: '소수 헌터',
    sequenceMaster: '시퀀스 마스터',
    divisionChallenge: '나눗셈 마스터',
    mentalArithmetic: '암산',
    mathFactMaster: '수학 사실',
    infiniteMathZen: '수학 명상',
    mathStream: '수학 스트림',
    reflexRush: '반사 러시',
    // Common game terms
    time: '시간',
    best: '최고',
    tap: '탭',
    start: '시작!',
    tapping: '탭하는 중...',
    newRecord: '🎉 신기록!',
    completed: '✅ 완료!',
    timeText: '시간',
    bestText: '최고',
    description: '1부터 25까지의 숫자를 순서대로 최대한 빠르게 탭하세요!',
    back: '뒤로',
    score: '점수',
    level: '레벨',
    correct: '정답!',
    wrong: '오답!',
    remember: '순서를 기억하세요!',
    yourTurn: '당신 차례!',
    patternComplete: '패턴 완성!',
    solve: '풀기:',
    answer: '답변',
    next: '다음',
    // New game terms
    streak: '연속',
    lives: '생명',
    gameOver: '게임 오버',
    playAgain: '다시하기',
    continue: '계속',
    quit: '종료',
    restart: '재시작',
    highScore: '최고 점수',
    average: '평균',
    reaction: '반응',
    speed: '속도',
    memory: '기억력',
    logic: '논리',
    math: '수학',
    reflex: '반사'
  },
  zh: {
    appName: 'Prime',
    selectLanguage: '选择语言',
    dashboard: '大脑训练',
    // Original challenges
    numberTap: '数字点击',
    mathSprint: '数学冲刺',
    memoryNumbers: '数字记忆',
    patternMatch: '模式匹配',
    // New challenges
    memoryMatrix: '记忆矩阵',
    patternPath: '模式路径',
    primeHunter: '质数猎手',
    sequenceMaster: '序列大师',
    divisionChallenge: '除法大师',
    mentalArithmetic: '心算',
    mathFactMaster: '数学事实',
    infiniteMathZen: '数学禅',
    mathStream: '数学流',
    reflexRush: '反射冲刺',
    // Common game terms
    time: '时间',
    best: '最佳',
    tap: '点击',
    start: '开始!',
    tapping: '点击中...',
    newRecord: '🎉 新纪录!',
    completed: '✅ 完成!',
    timeText: '时间',
    bestText: '最佳',
    description: '尽可能快地按顺序点击数字1-25！',
    back: '返回',
    score: '分数',
    level: '等级',
    correct: '正确!',
    wrong: '错误!',
    remember: '记住顺序！',
    yourTurn: '轮到你了！',
    patternComplete: '模式完成！',
    solve: '解决：',
    answer: '答案',
    next: '下一个',
    // New game terms
    streak: '连胜',
    lives: '生命',
    gameOver: '游戏结束',
    playAgain: '再玩一次',
    continue: '继续',
    quit: '退出',
    restart: '重新开始',
    highScore: '最高分',
    average: '平均',
    reaction: '反应',
    speed: '速度',
    memory: '记忆',
    logic: '逻辑',
    math: '数学',
    reflex: '反射'
  },
  ru: {
    appName: 'Prime',
    selectLanguage: 'Выбрать Язык',
    dashboard: 'Тренировка Мозга',
    // Original challenges
    numberTap: 'Числовой Тап',
    mathSprint: 'Математический Спринт',
    memoryNumbers: 'Память Чисел',
    patternMatch: 'Совпадение Паттернов',
    // New challenges
    memoryMatrix: 'Матрица Памяти',
    patternPath: 'Путь Паттернов',
    primeHunter: 'Охотник за Простыми',
    sequenceMaster: 'Мастер Последовательностей',
    divisionChallenge: 'Мастер Деления',
    mentalArithmetic: 'Устный Счёт',
    mathFactMaster: 'Математические Факты',
    infiniteMathZen: 'Математический Дзен',
    mathStream: 'Математический Поток',
    reflexRush: 'Рефлексный Рывок',
    // Common game terms
    time: 'Время',
    best: 'Лучший',
    tap: 'Нажми',
    start: 'Начать!',
    tapping: 'Нажимаем...',
    newRecord: '🎉 Новый Рекорд!',
    completed: '✅ Завершено!',
    timeText: 'Время',
    bestText: 'Лучший',
    description: 'Нажимайте числа 1-25 по порядку как можно быстрее!',
    back: 'Назад',
    score: 'Счет',
    level: 'Уровень',
    correct: 'Правильно!',
    wrong: 'Неправильно!',
    remember: 'Запомни последовательность!',
    yourTurn: 'Твоя очередь!',
    patternComplete: 'Паттерн Завершен!',
    solve: 'Реши:',
    answer: 'Ответ',
    next: 'Далее',
    // New game terms
    streak: 'Серия',
    lives: 'Жизни',
    gameOver: 'Игра Окончена',
    playAgain: 'Играть Снова',
    continue: 'Продолжить',
    quit: 'Выйти',
    restart: 'Перезапуск',
    highScore: 'Рекорд',
    average: 'Среднее',
    reaction: 'Реакция',
    speed: 'Скорость',
    memory: 'Память',
    logic: 'Логика',
    math: 'Математика',
    reflex: 'Рефлекс'
  },
  ar: {
    appName: 'Prime',
    selectLanguage: 'اختر اللغة',
    dashboard: 'تدريب الدماغ',
    // Original challenges
    numberTap: 'نقرة الرقم',
    mathSprint: 'سباق الرياضيات',
    memoryNumbers: 'ذاكرة الأرقام',
    patternMatch: 'مطابقة النمط',
    // New challenges
    memoryMatrix: 'مصفوفة الذاكرة',
    patternPath: 'مسار النمط',
    primeHunter: 'صائِد الأعداد الأولية',
    sequenceMaster: 'سيد التسلسل',
    divisionChallenge: 'سيد القسمة',
    mentalArithmetic: 'حساب ذهني',
    mathFactMaster: 'حقائق رياضية',
    infiniteMathZen: 'رياضيات زن',
    mathStream: 'تدفق الرياضيات',
    reflexRush: 'اندفاع الانعكاس',
    // Common game terms
    time: 'الوقت',
    best: 'الأفضل',
    tap: 'انقر',
    start: 'ابدأ!',
    tapping: 'جاري النقر...',
    newRecord: '🎉 رقم قياسي جديد!',
    completed: '✅ اكتمل!',
    timeText: 'الوقت',
    bestText: 'الأفضل',
    description: 'انقر على الأرقام من 1 إلى 25 بالترتيب بأسرع ما يمكن!',
    back: 'رجوع',
    score: 'النقاط',
    level: 'المستوى',
    correct: 'صحيح!',
    wrong: 'خطأ!',
    remember: 'تذكر التسلسل!',
    yourTurn: 'دورك!',
    patternComplete: 'اكتمل النمط!',
    solve: 'حل:',
    answer: 'الإجابة',
    next: 'التالي',
    // New game terms
    streak: 'سلسلة',
    lives: 'حياة',
    gameOver: 'انتهت اللعبة',
    playAgain: 'العب مرة أخرى',
    continue: 'استمر',
    quit: 'خرج',
    restart: 'إعادة التشغيل',
    highScore: 'أعلى درجة',
    average: 'متوسط',
    reaction: 'رد فعل',
    speed: 'سرعة',
    memory: 'ذاكرة',
    logic: 'منطق',
    math: 'رياضيات',
    reflex: 'انعكاس'
  },
  hi: {
    appName: 'Prime',
    selectLanguage: 'भाषा चुनें',
    dashboard: 'दिमागी प्रशिक्षण',
    // Original challenges
    numberTap: 'संख्या टैप',
    mathSprint: 'गणित स्प्रिंट',
    memoryNumbers: 'संख्या स्मृति',
    patternMatch: 'पैटर्न मिलान',
    // New challenges
    memoryMatrix: 'स्मृति मैट्रिक्स',
    patternPath: 'पैटर्न पथ',
    primeHunter: 'अभाज्य शिकारी',
    sequenceMaster: 'अनुक्रम मास्टर',
    divisionChallenge: 'विभाजन मास्टर',
    mentalArithmetic: 'मानसिक अंकगणित',
    mathFactMaster: 'गणित तथ्य',
    infiniteMathZen: 'गणित ज़ेन',
    mathStream: 'गणित धारा',
    reflexRush: 'रिफ्लेक्स रश',
    // Common game terms
    time: 'समय',
    best: 'सर्वश्रेष्ठ',
    tap: 'टैप',
    start: 'शुरू!',
    tapping: 'टैप कर रहे...',
    newRecord: '🎉 नया रिकॉर्ड!',
    completed: '✅ पूरा!',
    timeText: 'समय',
    bestText: 'सर्वश्रेष्ठ',
    description: '1-25 तक की संख्याओं को क्रम से जितनी तेजी से टैप कर सकते हैं!',
    back: 'वापस',
    score: 'स्कोर',
    level: 'स्तर',
    correct: 'सही!',
    wrong: 'गलत!',
    remember: 'अनुक्रम याद रखें!',
    yourTurn: 'आपकी बारी!',
    patternComplete: 'पैटर्न पूरा!',
    solve: 'हल करें:',
    answer: 'उत्तर',
    next: 'अगला',
    // New game terms
    streak: 'लगातार',
    lives: 'जीवन',
    gameOver: 'खेल समाप्त',
    playAgain: 'फिर से खेलें',
    continue: 'जारी रखें',
    quit: 'छोड़ें',
    restart: 'पुनः आरंभ',
    highScore: 'उच्च स्कोर',
    average: 'औसत',
    reaction: 'प्रतिक्रिया',
    speed: 'गति',
    memory: 'स्मृति',
    logic: 'तर्क',
    math: 'गणित',
    reflex: 'प्रतिवर्त'
  }
};

export type LanguageCode = keyof typeof LANGUAGES;